# Generated by Django 6.0.2 on 2026-02-25 15:56

from django.db import migrations
from django.conf import settings


def create_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")

    items_to_create = []
    # Get a list of groups from the settings.py file
    for group_name in settings.INITIAL_GROUPS:
        items_to_create.append(Group(name=group_name))

    Group.objects.bulk_create(items_to_create)


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]
