# Generated by Django 6.0.2 on 2026-02-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_create_groups"),
    ]

    operations = [
        migrations.CreateModel(
            name="IPBlocklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.CharField(
                        error_messages={"unique": "This IP is already blocked."},
                        max_length=128,
                        unique=True,
                        verbose_name="ip hash",
                    ),
                ),
            ],
        ),
    ]
